site_name: OPENTELEMETRY 文档
site_url: https://wdk-docs.github.io/opentelemetry-docs/
site_author: OPENTELEMETRY
site_description: OPENTELEMETRY 文档
docs_dir: content/en
site_dir: docs
dev_addr: 127.0.0.1:8001
extra_css:
  - stylesheets/extra.css

repo_name: wdk-docs/opentelemetry-docs
repo_url: https://github.com/wdk-docs/opentelemetry-docs
edit_uri: edit/master/content

theme:
  name: material
  logo: assets/logo/logo.svg
  favicon: assets/favicons/favicon.ico
  language: zh
  # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes # 父菜单索引
    # - navigation.sections # 全部展开
    # - navigation.expand # 打开收缩
    - content.code.annotate
    - navigation.top # 返回头部

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink

plugins:
  search:
    # Spaces, dashes, periods and forward-slash (so serving.knative.dev/blibble can be searched as blibble).
    separator: '[\/\s\-\.]+'
  # macros:
  #   module_name: hack/macros
  #   include_dir: source/snippets
  exclude:
    glob:
      # Exclude files that contain hugo specific shortcodes
      # (either the include shortcode or not-converted-yet tabs).
      - snippets/*
      - smoketest.md
  awesome-pages:
    filename: '.index'
    collapse_single_pages: true
    strict: false
  blogging:
    # GLOBAL CATEGORY: configs for {{ blog_content }}
    dirs:
      - blog
    # template: override/custom-blog.html

    # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
    categories:
      - name: reviews
        dirs:
          - reviews

    # GLOBAL CONFIG: configs apply to all categories
    time_format: '%Y-%m-%d'
    meta_time_format: '%Y-%m-%d'
    features:
      tags:
        index_page: tags.md
        insert: top

copyright: '版权所有 © 2017-2023 MIT by Sindre Sorhus'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sindresorhus
      name: Sindre Sorhus Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/sindresorhus
      name: Sindre Sorhus Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/sindresorhus
      name: Sindre Sorhus Instagram
    - icon: fontawesome/brands/blogger
      link: https://sindresorhus.com/apps
      name: Sindre Sorhus Blog
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@sindresorhus
      name: Sindre Sorhus Mastodon
  version_warning: !!python/object/apply:os.getenv ['VERSION_WARNING']
  knative_version: !!python/object/apply:os.getenv ['KNATIVE_VERSION']
  branch: !!python/object/apply:os.getenv ['SAMPLES_BRANCH', 'main']
  # analytics:
  #   provider: google
  #   property: G-YRMNFYE32R
  # version:
  #   provider: mike
nav:
  - 首页: index.md
  - 文档:
      - ./docs/index.md
      - ./docs/what-is-opentelemetry.md
      - 入门:
          - ./docs/getting-started/index.md
          - ./docs/getting-started/dev.md
          - ./docs/getting-started/ops.md
      - 概念:
          - ./docs/concepts/index.md
          - ./docs/concepts/observability-primer.md
          - 信号:
              - ./docs/concepts/signals/index.md
              - ./docs/concepts/signals/traces.md
              - ./docs/concepts/signals/metrics.md
              - ./docs/concepts/signals/logs.md
              - ./docs/concepts/signals/baggage.md
          - 仪表:
              - ./docs/concepts/instrumentation/index.md
              - ./docs/concepts/instrumentation/automatic.md
              - ./docs/concepts/instrumentation/manual.md
              - ./docs/concepts/instrumentation/libraries.md
          - ./docs/concepts/components.md
          - ./docs/concepts/semantic-conventions.md
          - docs/concepts/data-collection.md
          - 采样:
              - ./docs/concepts/sampling/index.md
          - SDK配置:
              - ./docs/concepts/sdk-configuration/index.md
              - ./docs/concepts/sdk-configuration/general-sdk-configuration.md
              - ./docs/concepts/sdk-configuration/otlp-exporter-configuration.md
          - ./docs/concepts/distributions.md
          - ./docs/concepts/glossary.md
      - 演示:
          - ./docs/demo/index.md
          - ./docs/demo/architecture.md
          - 采集器数据流仪表板:
              - ./docs/demo/collector-data-flow-dashboard/index.md
          - ./docs/demo/development.md
          - ./docs/demo/docker-deployment.md
          - ./docs/demo/feature-flags.md
          - ./docs/demo/features.md
          - ./docs/demo/forking.md
          - ./docs/demo/kubernetes-deployment.md
          - ./docs/demo/manual-span-attributes.md
          - ./docs/demo/metric-features.md
          - 需求:
              - ./docs/demo/requirements/index.md
              - ./docs/demo/requirements/application.md
              - ./docs/demo/requirements/architecture.md
              - ./docs/demo/requirements/opentelemetry.md
              - ./docs/demo/requirements/system.md
          - 场景:
              - ./docs/demo/scenarios/index.md
              - 建议缓存:
                  - ./docs/demo/scenarios/recommendation-cache/index.md
          - 演示截图:
              - ./docs/demo/screenshots/index.md
          - ./docs/demo/service-table.md
          - 服务:
              - ./docs/demo/services/index.md
              - ./docs/demo/services/accounting.md
              - ./docs/demo/services/ad.md
              - docs/demo/services/cart.md
              - docs/demo/services/checkout.md
              - docs/demo/services/currency.md
              - docs/demo/services/email.md
              - docs/demo/services/feature-flag.md
              - docs/demo/services/fraud-detection.md
              - docs/demo/services/frontend-proxy.md
              - docs/demo/services/frontend.md
              - docs/demo/services/kafka.md
              - docs/demo/services/load-generator.md
              - docs/demo/services/payment.md
              - docs/demo/services/product-catalog.md
              - docs/demo/services/quote.md
              - docs/demo/services/recommendation.md
              - docs/demo/services/shipping.md
          - ./docs/demo/tests.md
          - ./docs/demo/trace-features.md
      - 仪表:
          - ./docs/instrumentation/index.md
          - C++:
              - ./docs/instrumentation/cpp/index.md
              - ./docs/instrumentation/cpp/api.md
              - ./docs/instrumentation/cpp/examples.md
              - ./docs/instrumentation/cpp/exporters.md
              - ./docs/instrumentation/cpp/getting-started.md
              - ./docs/instrumentation/cpp/manual.md
          - .NET:
              - ./docs/instrumentation/net/index.md
              - docs/instrumentation/net/automatic.md
              - docs/instrumentation/net/examples.md
              - docs/instrumentation/net/exporters.md
              - docs/instrumentation/net/getting-started.md
              - docs/instrumentation/net/libraries.md
              - docs/instrumentation/net/manual.md
              - docs/instrumentation/net/metrics-api.md
              - docs/instrumentation/net/netframework.md
              - docs/instrumentation/net/resources.md
              - docs/instrumentation/net/shim.md
              - docs/instrumentation/net/traces-api.md
          - Erlang/Elixir:
              - ./docs/instrumentation/erlang/index.md
              - docs/instrumentation/erlang/api.md
              - docs/instrumentation/erlang/examples.md
              - docs/instrumentation/erlang/getting-started.md
              - docs/instrumentation/erlang/manual.md
              - docs/instrumentation/erlang/propagation.md
              - docs/instrumentation/erlang/resources.md
              - docs/instrumentation/erlang/sampling.md
              - docs/instrumentation/erlang/testing.md
          - Go:
              - ./docs/instrumentation/go/index.md
          - Java:
              - ./docs/instrumentation/java/index.md
              - docs/instrumentation/java/api.md
              - docs/instrumentation/java/examples.md
              - docs/instrumentation/java/getting-started.md
              - docs/instrumentation/java/manual.md
              - docs/instrumentation/java/automatic/index.md
              - docs/instrumentation/java/automatic/agent-config.md
              - docs/instrumentation/java/automatic/annotations.md
              - docs/instrumentation/java/automatic/extensions.md
          - JavaScript:
              - ./docs/instrumentation/js/index.md
              - 入门:
                  - ./docs/instrumentation/js/getting-started/index.md
                  - ./docs/instrumentation/js/getting-started/browser.md
                  - ./docs/instrumentation/js/getting-started/nodejs.md
              - 自动:
                  - ./docs/instrumentation/js/automatic/index.md
                  - ./docs/instrumentation/js/automatic/module-config.md
              - ./docs/instrumentation/js/manual.md
              - ./docs/instrumentation/js/libraries.md
              - ./docs/instrumentation/js/exporters.md
              - ./docs/instrumentation/js/context.md
              - ./docs/instrumentation/js/propagation.md
              - ./docs/instrumentation/js/resources.md
              - ./docs/instrumentation/js/sampling.md
              - ./docs/instrumentation/js/serverless.md
              - ./docs/instrumentation/js/api.md
              - ./docs/instrumentation/js/examples.md
          - PHP:
              - ./docs/instrumentation/php/index.md
              - docs/instrumentation/php/automatic.md
              - docs/instrumentation/php/examples.md
              - docs/instrumentation/php/exporters.md
              - docs/instrumentation/php/getting-started.md
              - docs/instrumentation/php/manual.md
              - docs/instrumentation/php/propagation.md
              - docs/instrumentation/php/resources.md
              - docs/instrumentation/php/sdk.md
          - Python:
              - ./docs/instrumentation/python/index.md
              - docs/instrumentation/python/api.md
              - docs/instrumentation/python/cookbook.md
              - docs/instrumentation/python/distro.md
              - docs/instrumentation/python/examples.md
              - docs/instrumentation/python/exporters.md
              - docs/instrumentation/python/getting-started.md
              - docs/instrumentation/python/manual.md
              - docs/instrumentation/python/mypy.md
              - docs/instrumentation/python/automatic/_index.md
              - docs/instrumentation/python/automatic/agent-config.md
              - docs/instrumentation/python/automatic/example.md
              - docs/instrumentation/python/automatic/operator.md
              - docs/instrumentation/ruby/api.md
          - Ruby:
              - ./docs/instrumentation/ruby/index.md
              - docs/instrumentation/ruby/automatic.md
              - docs/instrumentation/ruby/examples.md
              - docs/instrumentation/ruby/exporters.md
              - docs/instrumentation/ruby/getting-started.md
              - docs/instrumentation/ruby/manual.md
              - docs/instrumentation/ruby/sampling.md
          - Rust:
              - ./docs/instrumentation/rust/index.md
          - Swift:
              - ./docs/instrumentation/swift/index.md
              - docs/instrumentation/swift/libraries.md
              - docs/instrumentation/swift/manual.md
          - Other:
              - ./docs/instrumentation/other/index.md
      - 收集器:
          - ./docs/collector/index.md
          - ./docs/collector/getting-started.md
          - 部署:
              - ./docs/collector/deployment/index.md
              - ./docs/collector/deployment/agent.md
              - ./docs/collector/deployment/gateway.md
              - ./docs/collector/deployment/no-collector.md
          - ./docs/collector/configuration.md
          - ./docs/collector/management.md
          - ./docs/collector/distributions.md
          - ./docs/collector/troubleshooting.md
          - ./docs/collector/scaling.md
          - ./docs/collector/transforming-telemetry.md
          - ./docs/collector/custom-collector.md
          - ./docs/collector/custom-auth.md
          - ./docs/collector/trace-receiver.md
      - K8S:
          - ./docs/k8s/index.md
          - Operator:
              - ./docs/k8s/operator/index.md
              - ./docs/k8s/operator/automatic.md
              - api:
                  - ./docs/k8s/operator/apis/index.md
                  - ./docs/k8s/operator/apis/Instrumentation.md
                  - ./docs/k8s/operator/apis/OpenTelemetryCollector.md
          - Collector:
              - ./docs/k8s/collector/index.md
              - ./docs/k8s/collector/vision.md
              - ./docs/k8s/collector/design.md
              - ./docs/k8s/collector/monitoring.md
              - ./docs/k8s/collector/performance.md
              - ./docs/k8s/collector/security-best-practices.md
              - ./docs/k8s/collector/roadmap.md
              - ./docs/k8s/collector/ga-roadmap.md
              - ./docs/k8s/collector/observability.md
              - ./docs/k8s/collector/processing.md
              - ./docs/k8s/collector/release.md
              - ./docs/k8s/collector/scraping-receivers.md
              - ./docs/k8s/collector/service-extensions.md
              - ./docs/k8s/collector/standard-warnings.md
              - ./docs/k8s/collector/troubleshooting.md
      - FaaS:
          - ./docs/faas/index.md
          - ./docs/faas/lambda-auto-instrument.md
          - ./docs/faas/lambda-collector.md
          - ./docs/faas/lambda-manual-instrument.md
      - 迁移:
          - ./docs/migration/index.md
          - ./docs/migration/opencensus.md
          - ./docs/migration/opentracing.md
      - 规格:
          - ./docs/specs/index.md
          - ./docs/specs/status.md
          - ./docs/specs/otel.md
      - 致谢:
          - ./docs/acknowledgements/index.md
      - contribution-guidelines:
          - docs/contribution-guidelines.md
  - 生态系统:
      - ./ecosystem/index.md
      - ./ecosystem/demo.md
      - ./ecosystem/integrations.md
      - ./ecosystem/vendors.md
      - 注册表:
          - ./ecosystem/registry/index.md
          - ./ecosystem/registry/adding.md
  - 状态: status.md
  - 社区:
      - ./community/index.md
      - ./community/marketing-guidelines.md
      - enduser:
          - ./community/end-user/index.md
          - ./community/end-user/discussion-group.md
          - ./community/end-user/feedback-survey.md
          - ./community/end-user/interviews-feedback.md
          - ./community/end-user/otel-in-practice.md
          - ./community/end-user/slack-channel.md
  - 博客:
      - ./blog/index.md
      - blog/2019/opentelemetry-governance-committee-explained/index.md
      - blog/2021/auto-instrumentation-k8s.md
      - blog/2021/collector.md
      - blog/2021/cpp.md
      - blog/2021/gc-election.md
      - blog/2021/malabi.md
      - blog/2021/otel-gc.md
      - blog/2021/python.md
      - blog/2021/swift.md
      - blog/2021/womens-day.md
      - blog/2022/announcing-community-manager.md
      - blog/2022/dotnet-instrumentation-first-beta.md
      - blog/2022/dotnet-instrumentation-metrics.md
      - blog/2022/gc-candidates.md
      - blog/2022/gc-election-results.md
      - blog/2022/gc-elections.md
      - blog/2022/kubecon-na-project-update.md
      - blog/2022/kubecon-na.md
      - blog/2022/metrics-announcement.md
      - blog/2022/new-end-user-resources.md
      - blog/2022/otel-in-practice.md
      - blog/2022/otel-tuesday-v1-sunset.md
      - blog/2022/otel-unplugged-kubecon-na.md
      - blog/2022/troubleshooting-nodejs.md
      - blog/2022/v1.0-trio.md
      - blog/2022/welcome.md
      - blog/2022/announcing-opentelemetry-demo-release/index.md
      - blog/2022/apisix/index.md
      - blog/2022/collector-builder-sample/index.md
      - blog/2022/debug-otel-with-otel/index.md
      - blog/2022/demo-announcement/index.md
      - blog/2022/end-user-discussion-group-apac/index.md
      - blog/2022/exponential-histograms/index.md
      - blog/2022/frontend-overhaul/index.md
      - blog/2022/go-web-app-instrumentation/index.md
      - blog/2022/instrument-apache-httpd-server/index.md
      - blog/2022/instrument-kafka-clients/index.md
      - blog/2022/instrument-nginx/index.md
      - blog/2022/jaeger-native-otlp/index.md
      - blog/2022/k8s-metadata/index.md
      - blog/2022/k8s-otel-expose/index.md
      - blog/2022/knative/index.md
      - blog/2022/opamp/index.md
      - blog/2022/otel-demo-app-nomad/index.md
      - blog/2022/tail-sampling/index.md
      - blog/2022/why-and-how-ebay-pivoted-to-opentelemetry/index.md
      - blog/2023/ecs-otel-semconv-convergence.md
      - blog/2023/end-user-discussions-01.md
      - blog/2023/end-user-discussions-02.md
      - blog/2023/end-user-discussions-03.md
      - blog/2023/end-user-discussions-04.md
      - blog/2023/end-user-q-and-a-01.md
      - blog/2023/end-user-q-and-a-02.md
      - blog/2023/end-user-q-and-a-03.md
      - blog/2023/exponential-histograms.md
      - blog/2023/http-conventions-stability.md
      - blog/2023/kubecon-eu.md
      - blog/2023/lambda-release.md
      - blog/2023/new-apac-meetings.md
      - blog/2023/otel-in-focus-01.md
      - blog/2023/otel-in-focus-02.md
      - blog/2023/otel-in-focus-03.md
      - blog/2023/otel-in-focus-04.md
      - blog/2023/otel-in-focus-05.md
      - blog/2023/outreachy-may-cohort.md
      - blog/2023/php-beta-release.md
      - blog/2023/submitting-your-first-conference-talk.md
      - blog/2023/sunsetting-opencensus.md
      - blog/2023/demo-birthday/index.md
      - blog/2023/histograms-vs-summaries/index.md
      - blog/2023/jmx-metric-insight/index.md
      - blog/2023/k8s-runtime-observability/index.md
      - blog/2023/php-auto-instrumentation/index.md
      - blog/2023/why-histograms/index.md
  - 其它:
      - search.md
      - tags.md
